### PR TITLE
Simple pullrequest

### PR DESCRIPTION
**Pull request by netcode**

### CODE REVIEW

**Comment by netcode** [comment]
@shieldfy details about handlebars@4.1.0

**Comment by netcode** [comment]
@shieldfy details about Prototype Pollution

**Comment by netcode** [comment]
@shieldfy details about handlebars

**Comment by netcode** [comment]
@shieldfy can you ignore fstream vulnerability ?

**Comment by netcode** [comment]
@shieldfy fix fstream please

**Comment by netcode** [comment]
@shieldfy fix tar please

**Comment by netcode** [comment]
@shieldfy fix jquery

**Comment by hameed0z** [comment]
@shieldfy details about handlebars

**Pull request merged**
